export const offerData = [
  {
    id: 1,
    img: "https://promos.makemytrip.com/notification/xhdpi//Desktop-Group-Features-191222.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 2,
    img: "https://promos.makemytrip.com/notification/xhdpi//116X116-DH-CounterSale-22032023.jpg?im=Resize=(134,134)",
    hotelName: "AK FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 3,
    img: "https://promos.makemytrip.com/notification/xhdpi//116X116-yes-common-24032023.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 4,
    img: "https://promos.makemytrip.com/notification/xhdpi//Axis_DT_Flights.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 5,
    img: "https://promos.makemytrip.com/notification/xhdpi//132x132-DT-DH-Citi.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 6,
    img: "https://promos.makemytrip.com/notification/xhdpi//132x132-DT-IH-Citi.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 7,
    img: "https://promos.makemytrip.com/images//132x132-DT-Holidays-Citi.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 8,
    img: "https://promos.makemytrip.com/notification/xhdpi//Desktop_HoneymoonPackages_23Jan@2x.jpg?im=Resize=(134,134)",
    hotelName: "AK FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 9,
    img: "https://promos.makemytrip.com/images//132x132-DT-AT-cabs-Citi.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 10,
    img: "https://promos.makemytrip.com/notification/xhdpi//indigo-116x116-07072022.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 11,
    img: "https://promos.makemytrip.com/notification/xhdpi//116X116-IH-HoneyMoon-21112022.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 12,
    img: "https://promos.makemytrip.com/notification/xhdpi//Desktop-Group-Features-191222.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 13,
    img: "https://promos.makemytrip.com/notification/xhdpi//axisbank-116x116-27072022.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 14,
    img: "https://promos.makemytrip.com/appfest/xhdpi//SUV_9JAN.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 15,
    img: "https://promos.makemytrip.com/notification/xhdpi//116x116-IH-Bali-28122022.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },
  {
    id: 16,
    img: "https://promos.makemytrip.com/notification/xhdpi//Desktop_Pilgrimage_19July.jpg?im=Resize=(134,134)",
    hotelName: "DOM FLIGHTS",
    discountdesc: "Flat 12% Instant Discount on",
    discountCategory: "Domestic Flights!",
    discountCond: "Valid Only on Credit and Debit cards.",
  },

];

export const lockData = [
  {
    id: 1,
    image:
      "https://promos.makemytrip.com/notification/xhdpi/Vande-Flight-10072020.png",
    text: "Planning to book an international flight?",
    about: "Check Travel Guidelines",
  },
  {
    id: 2,
    image:
      "https://promos.makemytrip.com/Growth/Images/B2C/2x/language1@2x_20210901.png",
    text: "We are now availbale in Hindi!",
    about: "Change Language",
  },
  {
    id: 3,
    image:
      "https://promos.makemytrip.com/notification/xhdpi/web-check-in-116x116-23062020.png",
    text: "Complete your web check-in on MakeMyTrip in easy steps.",
    about: "Know More",
  },
];
